version: "3.7"
services:
  mongo-db:
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"
  bot:
    build:
      context: .
      dockerfile: docker/bot/DockerFile
    depends_on:
      - mongo-db
    environment:
      - DOCKER=1
    env_file:
      - .env
    restart: always
