[tool.poetry]
name = "mongo"
version = "0.1.0"
description = ""
authors = ["feDann <daniele99@ferrazzo.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
